[versions]
kotlin = "1.9.0"
klogging = "0.4.15"
jacoco = "0.8.8"
kotest = "5.6.2"
ktlint = "0.47.1"
slf4j = "2.0.7"
versions = "0.47.0"
html-reporter = "0.7.0"
spotless = "6.19.0"
reckon = "0.18.0"
publish = "1.1.0"

[libraries]
klogging = { module = "io.klogging:klogging-jvm", version.ref = "klogging" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
html-reporter = { module = "com.michaelstrasser:kotest-html-reporter", version.ref = "html-reporter" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
reckon = { module = "org.ajoberstar.reckon:reckon-gradle", version.ref = "reckon" }
publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "publish" }

[bundles]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
